services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rest_api:
    build: ./rest_api
    ports:
      - "5000:5000"
    depends_on:
      - mqtt
      - mongodb
    restart: on-failure

  subscriber:
    build: ./mqtt_client
    depends_on:
      - mqtt
      - mongodb
    restart: on-failure

  sensor1:
    build: ./sensors
    environment:
      - SENSOR_ID=1
      - ZONA=tomate
    depends_on:
      - mqtt
    restart: on-failure

  sensor2:
    build: ./sensors
    environment:
      - SENSOR_ID=2
      - ZONA=tomate
    depends_on:
      - mqtt
    restart: on-failure

  sensor3:
    build: ./sensors
    environment:
      - SENSOR_ID=3
      - ZONA=tomate
    depends_on:
      - mqtt
    restart: on-failure

  sensor4:
    build: ./sensors
    environment:
      - SENSOR_ID=4
      - ZONA=zanahoria
    depends_on:
      - mqtt
    restart: on-failure

  sensor5:
    build: ./sensors
    environment:
      - SENSOR_ID=5
      - ZONA=zanahoria
    depends_on:
      - mqtt
    restart: on-failure

  sensor6:
    build: ./sensors
    environment:
      - SENSOR_ID=6
      - ZONA=zanahoria
    depends_on:
      - mqtt
    restart: on-failure

  sensor7:
    build: ./sensors
    environment:
      - SENSOR_ID=7
      - ZONA=maiz
    depends_on:
      - mqtt
    restart: on-failure

  sensor8:
    build: ./sensors
    environment:
      - SENSOR_ID=8
      - ZONA=maiz
    depends_on:
      - mqtt
    restart: on-failure

  sensor9:
    build: ./sensors
    environment:
      - SENSOR_ID=9
      - ZONA=maiz
    depends_on:
      - mqtt
    restart: on-failure
    
  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - rest_api

volumes:
  mongo_data:
